apiVersion: apps/v1
kind: Deployment
metadata:
  name: fff
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      type: fff
  template:
    metadata:
      labels:
        type: fff
    spec:
      containers:
        - name: fff-container
          image: minseokgil/fff:v1.VERSION
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 5